set(SE_DEFAULT_OUTPUT_NAME "scratch-pc")

set(SE_RENDERER_VALID_OPTIONS "sdl1" "sdl2" "sdl3" "opengl" "opengl_core")
set(SE_AUDIO_ENGINE_VALID_OPTIONS "sdl1" "sdl2" "sdl3")
set(SE_DEPS_VALID_OPTIONS "source" "fallback" "system")
set(SE_LUA_BACKEND_VALID_OPTIONS "fallback" "lua51" "luajit")

set(SE_CACHING_DEFAULT ON)
set(SE_CMAKERC_DEFAULT ON)

set(SE_ALLOW_CMAKERC ON)
set(SE_ALLOW_CLOUDVARS ON)
set(SE_ALLOW_DOWNLOAD ON)
set(SE_DECTALK ON)

set(SE_PLATFORM_DEFINITIONS "__PC__")
set(SE_PLATFORM "pc")

set(SE_HAS_THREADS ON)

set(SE_HAS_TOUCH TRUE)
set(SE_HAS_MOUSE TRUE)
set(SE_HAS_KEYBOARD TRUE)
set(SE_HAS_CONTROLLER TRUE)

if(CMAKE_BUILD_TYPE MATCHES "Debug" AND NOT CMAKE_CROSSCOMPILING)
	set(SE_ASAN ON)
endif()

if(NOT BUILD_SHARED_LIBS AND MINGW)
	set(SE_STATIC_LIBGCC TRUE)
	set(SE_STATIC_LIBSTDCPP TRUE)
endif()

include(CheckSymbolExists)
check_symbol_exists(dlopen "dlfcn.h" SE_ALLOW_NATIVE_EXTENSIONS)

add_library(threads_interface INTERFACE)
find_package(Threads REQUIRED)
target_link_libraries(threads_interface INTERFACE Threads::Threads)

if(WIN32)
	macro(package_platform)
		set(CMAKE_SKIP_INSTALL_ALL_DEPENDENCY ON)
		install(TARGETS scratch-everywhere RUNTIME DESTINATION .)

		if(NOT SE_CMAKERC AND EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/romfs")
			install(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/romfs" DESTINATION .)
		endif()

		set(CPACK_PACKAGE_NAME "${SE_APP_NAME}")
		set(CPACK_PACKAGE_VENDOR "${SE_APP_AUTHOR}")
		set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${SE_APP_DESCRIPTION}")
		set(CPACK_PACKAGE_VERSION "${SE_APP_VERSION}")
		set(CPACK_PACKAGE_INSTALL_DIRECTORY "${SE_APP_NAME}")
		set(CPACK_PACKAGE_FILE_NAME "${SE_OUTPUT_NAME}-installer")
		set(CPACK_PACKAGE_EXECUTABLES "${SE_OUTPUT_NAME}" "${SE_APP_NAME}")
		set(CPACK_CREATE_DESKTOP_LINKS "${SE_OUTPUT_NAME}")
		set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")

		set(CPACK_GENERATOR "NSIS")
		set(CPACK_NSIS_MUI_ICON "${CMAKE_CURRENT_SOURCE_DIR}/gfx/windows/icon.ico")
		set(CPACK_NSIS_MUI_UNIICON "${CMAKE_CURRENT_SOURCE_DIR}/gfx/windows/icon.ico")
		set(CPACK_NSIS_INSTALLED_ICON_NAME "${SE_OUTPUT_NAME}.exe")
		set(CPACK_NSIS_DISPLAY_NAME "${SE_APP_NAME}")
		set(CPACK_NSIS_PACKAGE_NAME "${SE_APP_NAME}")
		set(CPACK_NSIS_URL_INFO_ABOUT "https://github.com/ScratchEverywhere/ScratchEverywhere")
		set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
		set(CPACK_NSIS_MODIFY_PATH OFF)

		include(CPack)
	endmacro()
endif()
