name: PC Nightly Build

on:
  push:
    paths:
      - CMakeLists.txt
      - cmake/platforms/pc.cmake
      - cmake/renderers/sdl2.cmake
      - cmake/windowing/sdl2.cmake
      - cmake/audio/sdl2.cmake
      - cmake/renderers/sdl1.cmake
      - cmake/windowing/sdl1.cmake
      - cmake/audio/sdl1.cmake
      - cmake/renderers/opengl.cmake
      - cmake/windowing/glfw.cmake
      - cmake/deps/*
      - source/runtime/**
      - source/platforms/
      - source/platforms/pc/**
      - source/renderers/sdl1/**
      - source/windowing/sdl1/**
      - source/audio/sdl1/**
      - source/renderers/sdl2/**
      - source/windowing/sdl2/**
      - source/renderers/sdl3/**
      - source/windowing/sdl3/**
      - source/audio/sdl2/**
      - source/audio/sdl3/**
      - source/renderers/opengl/**
      - source/renderers/opengl_core/**
      - source/windowing/glfw/**
      - source/renderers/headless/**
      - source/audio/headless/**
      - source/windowing/headless/**
      - source/*
      - source/menus/**
      - gfx/menu/**
      - include/**
      - .github/workflows/nightly-pc.yml
      - docker/Dockerfile.linux
      - docker/Dockerfile.windows
      - docker/Dockerfile.macos
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    name: Linux x86_64 ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Headless Library
            artifact: Scratch Everywhere! Linux Headless Library Nightly
            build-args: |
              RENDERER=headless
              WINDOWING=headless
              AUDIO_ENGINE=headless
              LIBRARY_MODE=TRUE
          - name: SDL2
            artifact: Scratch Everywhere! Linux SDL2 Nightly
            build-args: |
              RENDERER=sdl2
              WINDOWING=sdl2
              AUDIO_ENGINE=sdl2
          - name: SDL3
            artifact: Scratch Everywhere! Linux SDL3 Nightly
            build-args: |
              RENDERER=sdl3
              WINDOWING=sdl3
              AUDIO_ENGINE=sdl3
          - name: SDL1
            artifact: Scratch Everywhere! Linux SDL1 Nightly
            build-args: |
              RENDERER=sdl1
              WINDOWING=sdl1
              AUDIO_ENGINE=sdl1
          - name: Headless
            artifact: Scratch Everywhere! Linux Headless Nightly
            build-args: |
              RENDERER=headless
              WINDOWING=headless
              AUDIO_ENGINE=headless
          - name: OpenGL
            artifact: Scratch Everywhere! Linux OpenGL Nightly
            build-args: |
              RENDERER=opengl
              WINDOWING=glfw
              AUDIO_ENGINE=sdl3
              EXT_ARGS=-DSDL_WAYLAND=OFF
          - name: OpenGL Core
            artifact: Scratch Everywhere! Linux OpenGL Core Nightly
            build-args: |
              RENDERER=opengl_core
              WINDOWING=glfw
              AUDIO_ENGINE=sdl3
              EXT_ARGS=-DSDL_WAYLAND=OFF
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and Export
        uses: docker/build-push-action@v7
        with:
          context: .
          file: docker/Dockerfile.linux
          target: exporter
          outputs: type=local,dest=.
          build-args: ${{ matrix.build-args }}

      - name: Upload Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact }}
          path: scratch-pc
  windows:
    name: Windows x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and Export
        uses: docker/build-push-action@v7
        with:
          context: .
          file: docker/Dockerfile.windows
          target: exporter
          outputs: type=local,dest=.

      - name: Upload Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: Scratch Everywhere! Windows Nightly
          path: |
            scratch-pc.exe
            scratch-pc-installer.exe
  macos-intel:
    name: macOS x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and Export
        uses: docker/build-push-action@v7
        with:
          context: .
          file: docker/Dockerfile.macos
          target: exporter
          outputs: type=local,dest=.

      - name: Upload Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: Scratch Everywhere! macOS x86_64 Nightly
          path: scratch-pc
  macos-arm:
    name: macOS ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and Export
        uses: docker/build-push-action@v7
        with:
          context: .
          file: docker/Dockerfile.macos
          target: exporter
          outputs: type=local,dest=.
          build-args: ARCH=arm64

      - name: Upload Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: Scratch Everywhere! macOS ARM64 Nightly
          path: scratch-pc
  macos-universal:
    name: macOS Universal
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: [macos-arm, macos-intel]
    steps:
      - name: Download Intel Artifact
        uses: actions/download-artifact@v8
        with:
          name: Scratch Everywhere! macOS x86_64 Nightly
          path: intel-build
      - name: Download ARM Artifact
        uses: actions/download-artifact@v8
        with:
          name: Scratch Everywhere! macOS ARM64 Nightly
          path: arm-build
      - name: Download and Prepare lipo
        run: |
          curl -L -o lipo https://github.com/konoui/lipo/releases/download/v0.9.4/lipo_linux_amd64
          chmod +x lipo
      - name: Create Universal Binary
        run: ./lipo -output scratch-pc -create arm-build/scratch-pc intel-build/scratch-pc
      - name: Upload Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: Scratch Everywhere! macOS Universal Nightly
          path: scratch-pc
